### ISSUE TITLE
saved game syncing

### ISSUE THREAD

**Issue by erosson** [erosson/swarm#164]
looks like we can use dropbox or google accounts for this, though both require signin.
* alternatives discussion: http://stackoverflow.com/questions/22947152/data-store-apis
* alternatives discussion: https://www.reddit.com/r/androiddev/comments/2afaxm/alternatives_to_dropboxs_datastore_api/
* google drive sync: https://developers.google.com/drive/realtime/
  * example: https://realtimeplayground.appspot.com/#fileIds=0Bw-lz1vci7bxX3pfanhLR191NFE&userId=104955423417304081430
* dropbox sync: https://www.dropbox.com/developers/core/docs

google's game stuff looks promising, but I think it requires g+ and I don't have g+: https://developers.google.com/games/services/

there's also chrome.storage for chrome extensions, but that's chrome-specific and useless for mobile

looks like amazon has something that's easy to implement, but costs me money: https://aws.amazon.com/cognito/

**Comment by Shoelace** [comment]
ive had a look at most of these... i tnink the dropbox datastore api
https://www.dropbox.com/developers/datastore might be the easiest implementation..

i'll work on a fork to see if i can get this to go here.. https://github.com/Shoelace/swarm

i'll start with buttons for login, logout, load and save.  probably on the options page near the export string.
so it can be controlled manually..  then automatic save/updates can be added later

**Comment by Shoelace** [comment]
dropbox datastore api pull request at #260

**Comment by erosson** [comment]
#319

**Comment by erosson** [comment]
opted to have only one save slot. will make syncing easier once it's ready for that; simpler ui; less that can go wrong for a first release. can always add more slots later.

did some UI work. dropbox logos are all from their branding page. https://www.dropbox.com/developers/reference/branding

* logged out: ![image](https://cloud.githubusercontent.com/assets/238846/6184271/9a634154-b314-11e4-8ef1-f31c341617ed.png)
* logged in, no data: ![image](https://cloud.githubusercontent.com/assets/238846/6184274/a089fb22-b314-11e4-8a83-10db147246b6.png)
* logged in, with data: ![image](https://cloud.githubusercontent.com/assets/238846/6184283/b5b2bbce-b314-11e4-9ab1-51f37831925a.png)

**Comment by Shoelace** [comment]
ive checkedout these changes.. its lookign nice..

i see what you did with putting teh api key in the env in Grunfile.js.. thats clever.
is there a way i can override it easily?  i need to use my own as i need to set the correct  'Redirect URIs" for my server?  or do i just need to edit Gruntfile.js ?

* i think autosync is for files...  the syncing for the datastore part we are using is already handled via the line ```          datastore.recordsChanged.addListener( $scope.updatesavelisting );``` registers the callback such that whenever the data changes you get a call back.
if you have multiple tables. you can use ```event.affectedRecordsForTable()``` to filter for only the savegame table.
this would be where the 'auto-import' part would fit in.

* remember me is already handled i think.. doing the dropbox login/auth saves its own state in localstorage..

**Comment by erosson** [comment]
> is there a way i can override it easily?

There is now - try `grunt serve --dropboxAppKey=shoelaceDev` or `--dropboxAppKey=6hagxaf8041upxz`. Either should work; I gave the keys we've used so far names in the gruntfile. `--dropboxAppKey` should work with any grunt command.

I'm happy to add redirect uris to my dev key for you, but using your own key and doing it yourself is probably faster

> i think autosync is for files...

Okay. Glad you've already looked into that; thanks.

> remember me is already handled i think

Nice! I completely missed that while testing/reading.

**Comment by erosson** [comment]
Now (v1.0.9) usable in production builds with querystring `?dropbox=1`. Haven't applied for prod status with dropbox yet, so we're still limited to 100 people and this isn't ready for very wide distribution, but you (and any lurkers reading this) are welcome to use it until I do this.

**Comment by Shoelace** [comment]
okay.. i'll give it a try when i see 1.0.9
i dont know if you have tested.. but i know for my dev server i had to use https for dropbox to work.. ( i couldnt put a http url in the dropbox api redirect bit )  maybe its different for public urls..

**Comment by erosson** [comment]
yeah, it needed https for me too in most cases. testing on localhost didn't need https though.

**Comment by erosson** [comment]
Now works in prod, but images are missing. I'll fix this soon.

(new traffic from kongregate's a bit higher than I expected, keeping me busy!)

**Comment by Shoelace** [comment]
i've tried it now on prod..
yes teh images are broke.. but otherwise seems to work right.

FYI: you need to put the ?dropbox=1  before the #   .. otherwise it gets list when you swich pages.

i'll comment again later when i have tried import from anotehr machine..

**Comment by erosson** [comment]
> FYI: you need to put the ?dropbox=1 before the # .. otherwise it gets list when you swich pages.

I know, but angular's querystring-reader only works after the `#`, so this was easier. Since it's a temporary thing I didn't bother. Sorry about that.

**Comment by Shoelace** [comment]
no drama.. it was more a comment for any other lurkers out there.

**Comment by erosson** [comment]
Just now asked Dropbox for prod status, awaiting their reply.

**Comment by Shoelace** [comment]
ive tried this several times now.. and seems to be working ok.. 

the only issue i had was when i tried to do it on my mobile in chrome for ios..

i think it once you get the prod status it should move into standard beta mode.

**Comment by erosson** [comment]
https://mail.google.com/mail/u/0/#inbox/14bb4c0b2115891b

> Hi there,
> 
> Congratulations, your app's been upgraded to production status! You may now use your app key to make your app available to Dropbox users. Please keep in mind your app must follow the Dropbox branding guidelines.
> 
> Sincerely,
> - The Dropbox Platform Team

**Comment by Shoelace** [comment]
maybe you could consider hiding features behind a beta flag.
so much like env.isdebugenabled
but have it as an checkbox on the options screen.  or as a secret url.

so a feature can be rolled out but only a smaller number of people will use it initially?

**Comment by erosson** [comment]
I'm happy letting everyone at this one.

If I do decide to release something to only a small number, that's what [a/b tests](https://github.com/erosson/swarm/issues/355) will for - people get picked randomly. An opt-in on the options screen could work well for some cases, though.

**Comment by erosson** [comment]
Releasing this in prod. still need autosync and a kongregate solution (danged tos), but this is done enough to close.
