### ISSUE TITLE
engineering number format

### ISSUE THREAD

**Issue by Shoelace** [erosson/swarm#247]
I'd like to see numbers in engineering format..
ie like scientific.. but in multiples of 1e3

here is a basic patch i put together to enable this..

```
diff --git a/app/scripts/filters/bignum.coffee b/app/scripts/filters/bignum.coffee
index 66d5f7d..3adb663 100644
--- a/app/scripts/filters/bignum.coffee
+++ b/app/scripts/filters/bignum.coffee
@@ -42,6 +42,13 @@ angular.module('swarmApp').factory 'bignumFormatter', (options) ->
       # so hacky
       if options.notation() == 'hybrid'
         suffixes = suffixes.slice 0, 12
+      if options.notation() == 'engineering' 
+        #p = num.e; #Math.log10(num);
+        p = num.e - (num.e % 3);
+        e = Decimal.pow 10,p;
+        n = Math.floor(num.dividedBy e);
+        m = num.mod( e) ;
+        return n + "." + m.toFixed().substring(0,opts.sigfigs) +  "E" + p;
       if options.notation() == 'scientific-e' or index >= suffixes.length
         # too big for any suffix :(
         # TODO: exponent groups of 3? 1e30, 10e30, 100e30, 1e33, ...
diff --git a/app/scripts/services/options.coffee b/app/scripts/services/options.coffee
index b34807c..fe21861 100644
--- a/app/scripts/services/options.coffee
+++ b/app/scripts/services/options.coffee
@@ -44,7 +44,7 @@ angular.module('swarmApp').factory 'Options', ($log, util) -> class Options
 
   notation: (val) ->
     if val?
-      valid = {'standard-decimal':true, 'scientific-e':true, 'hybrid':true}
+      valid = {'standard-decimal':true, 'scientific-e':true, 'hybrid':true, 'engineering':true}
       util.assert valid[val], 'invalid options.notation value', val
       @maybeSet 'notation', val
     @get 'notation', 'standard-decimal'
```

**Comment by erosson** [comment]
Patch applied, with a few changes:
* (long overdue) unit test for every number format, including this one
* UI to select this on the options screen
* fixed/shortened sigfigs for consistency with other formats

This will appear on http://swarmsim-publictest.github.io first, and on http://swarmsim.github.io once the rest of v1.0 is ready. Changelog line links to this issue and to https://github.com/Shoelace .

Thank you!

**Comment by Shoelace** [comment]
wow.. that was quick..  great thanks..  

however i had bit of a brainwave in a dream last night..   

engineering format is identical to 'standard' format.. extecp you need to replace xxx-illion with the correct Exxx.


so i think a better version would be a version of the 'standard' format as follows

```
if options.notation() == 'engineering'
  num = num.dividedBy Decimal.pow 1000, index ;
  suffix = "E" + (index * 3)
  return "#{num.toPrecision(opts.sigfigs).replace(/\.$/, '')}#{suffix}"
```
thoughts?

do you like patches like this?  or would you prefer if i forked and offer pull requests instead?
(i have a few more planned .. )

Cheers

**Comment by erosson** [comment]
Probably cleaner to base it on standard-decimal, yeah. This stops the length from changing when the smallest digit is a zero, too. I'll change this shortly, thanks!

> do you like patches like this? or would you prefer if i forked and offer pull requests instead?
(i have a few more planned .. )

I'd like to try pull requests if you don't mind (though I wouldn't turn away patches). Looks like it'd be easier for me to comment that way. I've never actually done pull requests on github, but I'm sure I'll figure it out. :)

Btw, this project's GPLv2 licensed, so I assume your contributions are under the same license.

What other stuff are you thinking of adding?

**Comment by Shoelace** [comment]
yeah yeah..gpl is all good. 
i was hoping to add some improvements around the savegames..
in particular.. a check that you dont overwrite a newer game..  ie if new savetime is older then current save time ask for confirmation.  
which then leads onto dropbox datastore api support.
not really sure otherwise..  things that annoy me while i play.. :)

**Comment by erosson** [comment]
Cool. I looked at different ways to sync saved games a while back in #164 but never finished it, so I'd certainly accept a dropbox api patch.
