### ISSUE TITLE
allow exponential notation in number inputs

### ISSUE THREAD

**Issue by jepler** [erosson/swarm#271]
It would be nice if it worked to directly enter a number in scientific notation when buying multiple units.  The entry field itself seems to know what exponential numbers are (tested in ff, chrome with v1.0.0-publictest22), because pressing cursor up will transform e.g., 1e3 into 1001, and this trick can be used to enter an exponential and then change it by 1 unit, but eliminating this step would be nice.

I looked into this a bit and it could be a limitation of angular.js, which assumes that numbers are made up of an optional sign, decimal digits, and an optional decimal point: https://github.com/angular/angular.js/blob/master/src/ng/directive/input.js#L16 http://stackoverflow.com/questions/24933472/angularjs-input-fails-for-big-numbers-in-scientific-notation

**Comment by jepler** [comment]
.. just specifying ng-pattern is insufficient, because the NUMBER_REGEXP is hardcoded in numberInputType.  https://github.com/angular/angular.js/blob/master/src/ng/directive/input.js#L1239

**Comment by erosson** [comment]
Thanks for looking into this! Unfortunate that angular makes it difficult. Looks like it's possible to hack around angular to get the value with jquery, at least in Chrome:

> $('input').val()
> "1e300"

Numbers above `Number.MAX_VALUE` still don't work, but it's an improvement. I'll take a closer look at this later.
