### ISSUE TITLE
better control over upgrade-available visibility

### ISSUE THREAD

**Issue by erosson** [erosson/swarm#294]
it's annoying to have upgrades reappear after a page refresh, and to see upgrade notifications you don't care about.

add a "show available upgrades" checkbox next to each upgrade, and only show notifications for those upgrades. scrap the ignore-when-viewed system that's there now.

**Comment by erosson** [comment]
a visual indicator for unwatched upgrades - graying them out - would go well with this: https://www.reddit.com/r/swarmsim/comments/2vpv9o/suggestion_option_to_grey_out_select_upgrades/

**Comment by Shoelace** [comment]
this update is awesome.. love it..
