### ISSUE TITLE
remove the statistics screen

### ISSUE THREAD

**Issue by erosson** [erosson/swarm#316]
I haven't updated it in ages, it's probably all broken. Verify it's not getting much traffic first.

**Comment by erosson** [comment]
on second thought, leave it. it's working fine, surprisingly.

let's remove the obsolete click-logging stuff at the bottom though.

**Comment by Shoelace** [comment]
sounds like a plan..

can i suggest we add 
* date started or last reset date/time 
* first/last ascend times?

**Comment by erosson** [comment]
Ascension times weren't tracked before now - oops! Now ascensions appear as a regular unit on the statistics screen, which is a little weird but it's the easiest implementation and I don't want to spend lots of time on the stats screen.
