### ISSUE TITLE
game not loading for some folks on kong

### ISSUE THREAD

**Issue by erosson** [erosson/swarm#340]
https://mail.google.com/mail/u/0/#inbox/14b9b4c9dbfbcacd

https://mail.google.com/mail/u/0/#inbox/14b9c01a69b7ef26

plus some complains of a blank screen in comments

**Comment by Shoelace** [comment]
FYI.. those mail links only work for you..

**Comment by erosson** [comment]
some browsers' third-party cookie settings wont' even let me try to read them - that's what was happening here. now shows an error.
