### ISSUE TITLE
missing achievement progress bars in ie-ish browser

### ISSUE THREAD

**Issue by erosson** [erosson/swarm#358]
froma feedback form report: http://imgur.com/SAVclyP

works fine in chrome, v1.0.13. user-agent: "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; Tablet PC 2.0; rv:11.0) like Gecko" - not a common one; trident is IE i think but my spreadsheet's browser-identifier doesn't think so. need to test in IE.

**Comment by Shoelace** [comment]
confirmed.. on internet explorer 11 i get no progress bars at all.

Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko

but i also seem to have foudn the issue.

a DOM inspection says the <div class="progress-bar "...  has an inline style of 
width:{{upgrade.costMetPercent()|percent:1}

and not "3.2%"

also the aria-valuenow  is also ""12312321""   (ie  with 2 double quotes at each end )

**Comment by Shoelace** [comment]
it maybe related., but i get to console errors..
Unable to get property 'module' of undefined or null reference
File: scripts.628c6269.js, Line: 1, Column: 26

which corresoponds to 
```angular.module("swarmApp",["ngAnimate","ngCookies","ngResource","ngRoute","ngSanitize","ngTouch","swarmEnv","swarmSpreadsheetPreload","angulartics","angulartics.google.analytics"])```

and 
SCRIPT5007: Unable to get property 'min' of undefined or null reference
File: vendor.3a12a71c.js, Line: 6, Column: 18116

which is
```for(var h=a.$dv,i=h===c?Math.min(g,1):g,j=0;i>j;j++)```


this is on production v1.0.15

**Comment by Shoelace** [comment]
i was able to get progress bars in IE if i switched to using http://angular-ui.github.io/bootstrap/#/progressbar  but that would be a largish change i think.

**Comment by erosson** [comment]
wow, this breaks for *any* progressbar on IE. I'm sure I tested this at some point...

**Comment by erosson** [comment]
ie doesn't like `style="{{variable}}"`. ng-style works.

**Comment by Shoelace** [comment]
i had tried switching to nf-style.. but i see it was a little bit more complicated..  ill cancel #365
