### ISSUE TITLE
asymptotic upgrades are causing confusion

### ISSUE THREAD

**Issue by erosson** [erosson/swarm#363]
see what we can do to make it clearer

**Comment by erosson** [comment]
still lots of complaints about this. "1000 lepi gave 50%, so 2000 shoudl give 100%!"

**Comment by Shoelace** [comment]
maybe use the phrase "diminishing returns"  maybe somehting like

"Your lepidoptera generate 75.00% more energy. Hatching more will have diminshing returns but can increase this to a maximum of 100%."

**Comment by erosson** [comment]
That's a good way to phrase it. Thanks!

bumping the priority up on this, since the fix is pretty easy and it keeps coming up.
