### ISSUE TITLE
write a proper dark theme, not inverted-colors

### ISSUE THREAD

**Issue by erosson** [erosson/swarm#370]
current dark theme based on inverting the white theme is causing all kinds of trouble. #369, #364, #368, https://www.reddit.com/r/swarmsim/comments/2wljhi/bug_zooming_with_theme/ ,not to mention the whole browser-specific part being messy

**Comment by erosson** [comment]
actually, writing my own theme is too hard. I knew someone had already done it for me, no idea why I never found it before:

https://stackoverflow.com/questions/19192747/how-to-dynamically-change-themes-after-clicking-a-drop-down-menu-of-themes
http://bootswatch.com/

demo http://jsfiddle.net/82AsF/ , verified to work in ff/ie/chrome (though obviously integrating with swarmsim requires new tests)

**Comment by Shoelace** [comment]
cool..  10 themes from http://bootswatch.com/  is better then 1.. :)

i suggest you just implement it as is... an dallow any of them themes from http://bootswatch.com/
david

Date: Sat, 21 Feb 2015 14:39:44 -0800

**Comment by erosson** [comment]
agreed - you can now choose from any theme on http://bootswatch.com/ . probably a good idea to prioritize the most commonly chosen themes since the list is a bit intimidating, but it's a good start. anyone using the old dark themes is now using "slate".

I'm thinking "slate" will become the default, too - with a link to switch to the current white theme on the first tutorial screen for people starting at work/where a dark screen isn't discreet enough. not yet, though - should get analytics to track which themes people like before deciding.

plus, you can set a custom theme css url: people can create and distribute their own themes. (so my new answer to "the theme is ugly" can be "you fix it" :P )
