### ISSUE TITLE
kong: redirect to http if https fails

### ISSUE THREAD

**Issue by erosson** [erosson/swarm#401]
#357 and #337 are certainly both ssl problems. if ssl's broken, let people play on non-ssl. we now support cookies and flash, so odds are their save will be available on both - but do account for localstorage

**Comment by jrynd** [comment]
If a user's SSL is broken, shouldn't they know about the potential security issue rather than hiding it from them?

**Comment by erosson** [comment]
You're right - of course we should tell them, thanks for pointing this out. This should definitely have some sort of alert "hey, connecting to swarmsim via SSL didn't work, you should make sure https://www.howsmyssl.com/ thinks everything's cool".

Everyone who's got back to me about SSLv3 errors says https://www.howsmyssl.com/ and https://filippo.io/Badfish/ say they're fine, though - #337. I'm kind of out of ideas besides "work around it", but it's still worth telling them something might be up.

**Comment by erosson** [comment]
dang, this won't work after all.

I was counting on hosting `kongregate_shell.html` from http://www.swarmsim.com to do the redirect, but that's cross-domain for https://www.swarmsim.com . that breaks using it for keeping the kongregate api scripts loaded across refreshes. could work around that with a second frame at http - but we must also have same-origin access the top frame for our custom autoresize/scrolling to work. we can't nest frames like https -> http -> https to work around *that* because mixed content.
